import Head from "next/head";
import Layout from "../../components/layout";
import { getPortfolioItem, getPortfolioSlugs } from "../../lib/data";
import { useRouter } from "next/router";

export const getStaticPaths = async () => {
  const slugRes = await getPortfolioSlugs();
  const slug = slugRes.portfolios;
  return {
    paths: slug.map((slug) => ({ params: { slug: slug.slug } })),
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const portfolioItem = await getPortfolioItem(params.slug);

  return {
    props: {
      portfolioItem: portfolioItem.portfolios[0],
    },
  };
};

const Home = ({ portfolioItem }) => {
  const router = useRouter();

  if (router.isFallback) {
    return <div>Loading...</div>;
  }
  console.log(portfolioItem);
  return (
    <Layout>
      <Head>
        <title>Awesome Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>{portfolioItem.title}</h1>
      </div>
    </Layout>
  );
};

export default Home;
